name: CICD pipeline
on: 
  push:
    branches:
      - dev/**
    paths:
      - 'src/server.js'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  build:
    name: Checkout & Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source-code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        npm install

    - name: Build nodejs app
      run: |
        # npm build
        echo "Build step - skipped"

    - name: Package application
      run: |
        zip -r app-package.zip .

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-package
        path: app-package.zip

  sonarqube:
    name: Sonarqube Scan
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source-code
        uses: actions/checkout@v4

      - name: Sonarqube Scan
        uses: sonarsource/sonarcloud-github-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy
    if: github.ref_name == 'master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download application package
        uses: actions/download-artifact@v4
        with:
          name: app-package

      - name: unzip application package
        run: |
          unzip ./app-package.zip -d ./node-app

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start application server & tunnel
        run: |
          node ./node-app/src/server.js &
          npx localtunnel --port 3000 &

          sleep 5
          echo "Application server is available on tunnel"

          echo "Your tunnel password is: $(curl ifconfig.me)"

          sleep 120
          echo "Shutting down application server"