name: CICD pipeline
on: 
  push:
    branches:
      - dev/**
    paths:
      - 'src/server.js'
      - 'package.json'
  workflow_dispatch:

jobs:
  build:
    name: Checkout & Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source-code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        npm install

    - name: Build nodejs app
      run: |
        # npm build
        echo "Build step - skipped"

    - name: Package application
      run: |
        zip -r app-package.zip .

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-package
        path: app-package.zip

  # sonarqube:
  #   name: Sonarqube Scan
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source-code
  #       uses: actions/checkout@v4

  #     - name: Sonarqube Scan
  #       uses: SonarSource/sonarqube-scan-action@v7.0.0
  #       env:
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #         SONAR_HOST_URL: https://sonarcloud.io

  # sca-scan:
  #   name: SCA Scan
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source-code
  #       uses: actions/checkout@v4

  #     - name: SCA Scan using Anchore Grype Scan
  #       uses: anchore/scan-action@v6
  #       with:
  #         path: "."
  #         output-format: "table"

  deploy:
    name: Deploy
    # if: github.ref_name == 'master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download application package
        uses: actions/download-artifact@v4
        with:
          name: app-package

      - name: unzip application package
        run: |
          unzip ./app-package.zip -d ./node-app

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Start application server & expose to internet
        run: |
          node ./node-app/src/server.js &
          # npx localtunnel --port 3000 &

          # npx bore-node local 3000 --to bore.pub &

          # ssh -o StrictHostKeyChecking=no -R 80:localhost:3000 serveo.net &

          ssh -p 443 -o StrictHostKeyChecking=no -R0:localhost:3000 a.pinggy.io &

          sleep 5
          echo "Application server is available on tunnel"
          echo "GitHub Runner's public IP: $(curl ifconfig.me)"

          sleep 120
          echo "Shutting down application server"

  # dast-scan:
  #   name: DAST Scan
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run DAST Scan using zaproxy
  #       uses: zaproxy/action-baseline@v0.15.0
  #       with:
  #         target: 'http://localhost:3000/'
  #         token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}